### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by CallMeFib3r** [AdamMc331/CashCaretaker#133]
Hi @AdamMc331 331,

Your CashCaretaker app is helping out a lot of people and I figured I, a hobbyist graphic designer, could help you and the project out with a fresh logo that suits the project and stands out from the competition. Before we proceed to my draft I would like to state that this concept is completely FREE of charge. I will provide you with all the files as well as the proper license if you decide to use the concept. 

Please allow me to present my proposal.

For this project specifically, I wanted to represent the app itself yet maintaining the fundamentals of the old logo. Therefore I cleaned up the dollar sign by rounding corners and putting everything in the right proportions. To directly integrate the 'caretaking' element of the app I went ahead and added in a hand which represents the app taking care of the users' funds. To (literally) wrap up the composition I added a rotated C which is a direct reference to the title of the app.

![cashcaretaker-08](https://user-images.githubusercontent.com/37731582/40587618-e820de50-61d1-11e8-8410-bf10097b2f07.png)

Here's a comparison with the current logo and my proposal.

![comparison-09](https://user-images.githubusercontent.com/37731582/40587619-e83c7c46-61d1-11e8-8b06-e03e7b06b8ae.png)
The colors used are a lot more appealing and make the app stand out from competitors.

If you'd like me to make changes here and there feel free to let me know. 
If you like the current proposal and are interested in integrating it into project let me know and I will provide with all the files and open a pull-request with your permission of course.

Have a wonderful day,

Fiber

**Comment by AdamMc331** [comment]
I think this looks great! I'll be away from a computer for a bit but I'm happy to discuss this. Can you send the license you mentioned to amcneilly331@gmail.com so I can read it over first?

**Comment by rashiq** [comment]
you are a very cool person @CallMeFib3r
