### ISSUE TITLE
Strip Out Content Provider

### ISSUE THREAD

**Issue by AdamMc331** [AdamMc331/CashCaretaker#20]
While having a ContentProvider is nice and works for the super simple CRUD things, I'm tired of writing new URIs every time I need them when it's a bit unnecessary, since this app doesn't display any data externally.

The CCProvider class will be replaced by CCDataSource which will run all of our operations.

NOTE: With overhauls like this, the milestone might turn into 2.0.

**Comment by AdamMc331** [comment]
Okay I started doing this and I am reconsidering.

**Comment by TristanWiley** [comment]
lol
