### ISSUE TITLE
Add google analytics for better app tracking.

### ISSUE THREAD

**Issue by AdamMc331** [AdamMc331/CashCaretaker#22]

**Comment by Mauker1** [comment]
What about [fabric](https://get.fabric.io/)?

**Comment by AdamMc331** [comment]
Also a really good idea. There's no reason both can't be implemented.

From my minimal experience at work: fabric is good for detecting things like active users, and crash logs, but Google Analytics is good at tracking events. So if I wanted to get detailed analytics on how often users are adding new accounts and transactions, or using the detailed features like repeating transactions, I could use that to help prioritize.

**Comment by AdamMc331** [comment]
@Mauker1 I have implemented fabric for issue #24 . I am considering using Answers to track specific user events, do you have any ideas of what should be tracked? If you do, drop a comment on that ticket and I'll see what I can do.

**Comment by AdamMc331** [comment]
Meh nvm I'll add tracking in the future. Right now I'll just use Answers for tracking active users and things like that. Closing this ticket because if I chose analytics I'll just use Fabric.
