### ISSUE TITLE
Improve Wearable performance 

### ISSUE THREAD

**Issue by AdamMc331** [AdamMc331/CashCaretaker#27]
After watching the Udacity course on Wear development, I realized I'm using poor development decisions on Wear.

We should use Data Items instead of Messages, since they are always guaranteed to be delivered when the Watch/Phone sync up. In addition, we should reduce the amount of operations the watch is doing to save battery. We should consider having the watch request information from the phone when the watch activity starts, and the phone will spit back a response and the watch can cache it as necessary. 

Planning to do a release focused on this: 1.4.2

**Comment by Mauker1** [comment]
Interesting idea! I'd like to see the modifications.
