### ISSUE TITLE
Large numbers mess up layout, edge case

### ISSUE THREAD

**Issue by TristanWiley** [AdamMc331/CashCaretaker#54]
Text messes up layout if number is too big

![23846750_1714580618560288_2057532435_o](https://user-images.githubusercontent.com/2747793/33053732-263fbf08-ce43-11e7-8a37-3a066fbddf79.png)
![23847937_1714580541893629_945442120_o](https://user-images.githubusercontent.com/2747793/33053734-2757b3f0-ce43-11e7-8b52-5ad6efb3391d.png)

**Comment by Mauker1** [comment]
Also experienced this

**Comment by AdamMc331** [comment]
@TristanWiley What do you think of this fix?

![cc54](https://user-images.githubusercontent.com/9515997/33247966-f6a42480-d2ef-11e7-9aa9-f91fde7bf555.png)
